#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

echo -n "Creating flowee user... "
grep -E "^flowee:" /etc/group >/dev/null || groupadd flowee
useradd -m -d /etc/flowee -g flowee -s /usr/bin/nologin flowee 2>/dev/null
echo "done"

_datadir="/var/lib/flowee"

if test ! -d "$_datadir"; then
  mkdir -m 750 "$_chaindir"
fi
mkdir -p -m 770 "/var/log/flowee"
chown -R flowee:flowee "/var/log/flowee" "/var/lib/flowee" "/etc/flowee"

#DEBHELPER#
