#!/bin/sh -e

echo -n "Creating flowee user... "
groupadd -fr flowee
useradd -r -m -d /etc/flowee -g flowee -s /usr/sbin/nologin flowee 2>/dev/null
echo "done"

_datadir="/var/lib/flowee"

if test ! -d "$_datadir"; then
  mkdir -m 750 "$_datadir"
fi
mkdir -p -m 770 "/var/log/flowee"
chown -R flowee:flowee "/var/log/flowee" "$_datadir" "/etc/flowee"
